# Generated by Django 5.1.1 on 2024-09-10 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecvs', '0002_credential_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='credential',
            name='private_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='credential',
            name='public_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('encrypted_private_key', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
