# Generated by Django 5.1.1 on 2024-09-10 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecvs', '0004_remove_credential_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
